version: "3.7"

services:
#  mysql:
#    image: mysql:5.7.26
#    command: '--default-authentication-plugin=mysql_native_password'
#    ports:
#      - 8889:3306
#    volumes:
#      - ./storage/:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#
#  wordpress:
#    depends_on:
#      - mysql
#    image: wordpress:5.2.2-php7.3-apache
#    ports:
#      - 8080:80
#    volumes:
#      - ./src:/var/www/html/wp-content/plugins/lorem-user-generator
#    working_dir: /var/www/html
#    environment:
#      WORDPRESS_DB_HOST: mysql:3306
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_PASSWORD: root
#      WORDPRESS_DB_NAME: wordpress-sandbox
#      WORDPRESS_DEBUG: 1

  php:
    container_name: lorem-user-generator-php
    build: ./.docker/php
    volumes:
      - ./src:/app/src
      - ./vendor:/app/vendor
    working_dir: /app
  composer:
    container_name: lorem-user-generator-composer
    build: ./.docker/composer
    links:
      - php
    restart: 'no'
    volumes:
      - ./src:/app/src
      - ./vendor:/app/vendor
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
    working_dir: /app
    command: install --ignore-platform-reqs
volumes:
  storage: {}


